spring:
  application:
    name: castgroup
  datasource:
    url: jdbc:h2:mem:contas
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:contas
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    enabled: true

server:
  port: 9092
