spring:
  application:
    name: castgroup
  datasource:
    url: jdbc:h2:mem:contas
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
server:
  port: 9092
